//import './bind'
// import './extend'
import './promise'
//import './type'
// import './curry'
// import './eventLoop'
// import './lazyMan'
// import './generator'
// import './ajax'
// import './defineProperty'
// import './useStrict'
// import './proxy'